### ISSUE TITLE
Confusion about the results of NYU v2 2-task

### ISSUE THREAD

**Issue by slyviacassell** [sunxm2357/AdaShare#6]
Hi Ximeng, 
    I am reading your NIPS2020 publication "AdaShare: LearningWhatToShareForEfﬁcient DeepMulti-TaskLearning
" and I am also confused about the reported results of NYU v2 2-task. I find that the performance of NDDR-CNN is lower than what was reported in the original paper.  Does this is caused by the difference of backbone or other settings? Would you mind providing more details? Thank you very much!

**Comment by sunxm2357** [comment]
Thanks for your interest in our paper! 
I think there are two main reasons to cause the difference. 1. They are using VGG16 based architecture and we are using ResNet18 based models. 2. They use the imagenet pre-trained weights as the initialization. However, in our work, we do not use any pre-trained networks for a fair comparison among all models. If you run our code using the imagenet pretrained weights, the performance will be improved. For example, for NYU-v2 3 tasks, we observe that the pre-trained weight improves our overall performance by 11.3%.

**Comment by slyviacassell** [comment]
I think these make sense. Thank you for your prompt and sincere reply!
