### ISSUE TITLE
Can you share your files of the Taskonomy dataset?

### ISSUE THREAD

**Issue by zhanglijun95** [sunxm2357/AdaShare#7]
Hi there,

Can you share your files, taskonomy.json and semseg_prior_factor.npy, of the Taskonomy dataset? Thank you very much!

**Comment by sunxm2357** [comment]
semseg_prior_factor.npy can be found on taskonomy's github: https://github.com/StanfordVL/taskonomy/tree/master/taskbank/lib/data

taskonomy.json can be found at https://drive.google.com/drive/folders/1KX9chooxefvrZACtFR441ShdkbS3F2lt?usp=sharing

**Comment by hohohoho1111** [comment]
Thanks for your release code!

Can you share new version of taskonomy.json? Now, The path is not matched because that dataset is updated

Additionally, How did you split dataset(nyu_v2, cityscape) into train1, train2?
